### ISSUE TITLE
error when PR triggers hook? PR and hooks work, but error is received 

### ISSUE THREAD

**Issue by steveb85** [marshalhayes/gitbucket-githooks-plugin#11]
**Describe the bug**

**To reproduce**
merge any PR (i’m doing it between forks) where the base fork will trigger a post receive hook

**Expected behavior**
everything actually works, i just get the following error.

**Screenshots**

Internal Server Error
java.lang.NullPointerException
io.github.gitbucket.githook.hook.PRHook.$anonfun$merged$2(PRHook.scala:41)
scala.util.Using$.resource(Using.scala:261)
io.github.gitbucket.githook.hook.PRHook.merged(PRHook.scala:36)
gitbucket.core.service.MergeService.$anonfun$mergePullRequest$15(MergeService.scala:460)
gitbucket.core.service.MergeService.$anonfun$mergePullRequest$15$adapted(MergeService.scala:458)
scala.collection.immutable.List.foreach(List.scala:333)
gitbucket.core.service.MergeService.$anonfun$mergePullRequest$3(MergeService.scala:458)
scala.util.Using$.resource(Using.scala:261)
gitbucket.core.service.MergeService.$anonfun$mergePullRequest$2(MergeService.scala:339)
scala.Option.map(Option.scala:242)
gitbucket.core.service.MergeService.$anonfun$mergePullRequest$1(MergeService.scala:337)
gitbucket.core.util.LockUtil$.lock(LockUtil.scala:30)
gitbucket.core.service.MergeService.mergePullRequest(MergeService.scala:470)
gitbucket.core.service.MergeService.mergePullRequest$(MergeService.scala:324)
gitbucket.core.controller.PullRequestsController.mergePullRequest(PullRequestsController.scala:20)
gitbucket.core.controller.PullRequestsControllerBase.$anonfun
i
n
i
t
init63(PullRequestsController.scala:378)
gitbucket.core.controller.PullRequestsControllerBase.$anonfun
i
n
i
t
init63$adapted(PullRequestsController.scala:377)
scala.Option.flatMap(Option.scala:283)
gitbucket.core.controller.PullRequestsControllerBase.$anonfun
i
n
i
t
init62(PullRequestsController.scala:377)
gitbucket.core.controller.Context.withLoginAccount(ControllerBase.scala:305)
gitbucket.core.controller.PullRequestsControllerBase.$anonfun
i
n
i
t
init61(PullRequestsController.scala:376)
gitbucket.core.util.WritableUsersAuthenticator.$anonfun$writableUsersOnly$2(Authenticator.scala:130)
gitbucket.core.util.WritableUsersAuthenticator.$anonfun$authenticate$8(Authenticator.scala:138)
scala.Option.map(Option.scala:242)
gitbucket.core.util.WritableUsersAuthenticator.authenticate(Authenticator.scala:136)
gitbucket.core.util.WritableUsersAuthenticator.$anonfun$writableUsersOnly$1(Authenticator.scala:130)
gitbucket.core.controller.ValidationSupport.$anonfun$post$3(ValidationSupport.scala:25)
org.scalatra.forms.FormSupport.validate(FormSupport.scala:14)
org.scalatra.forms.FormSupport.validate$(FormSupport.scala:8)
gitbucket.core.controller.ControllerBase.validate(ControllerBase.scala:36)
gitbucket.core.controller.ValidationSupport.$anonfun$post$1(ValidationSupport.scala:25)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:180)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:36)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:36)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
scala.Option.flatMap(Option.scala:283)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
scala.collection.immutable.Stream.flatMap(Stream.scala:204)
org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:36)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:36)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.wi

**Additional context**

**Comment by steveb85** [comment]
using gitbucket 4.37.2 (latest)

**Comment by steveb85** [comment]
@marshalhayes didn’t realize there was a 1.1.1 available, that seems to have fixed this issue.

**Comment by marshalhayes** [comment]
Glad to see that you were able to resolve the issue by upgrading. 

I need to eventually look into marking v1.1.1 as non-prerelease. Does everything appear to be working with v1.1.1?

**Comment by steveb85** [comment]
everything appears to be working fully @marshalhayes  thanks for checking in!
