### ISSUE TITLE
[Feature Request] Add support for pre-receive

### ISSUE THREAD

**Issue by marshalhayes** [marshalhayes/gitbucket-githooks-plugin#3]
I'd like to add support for the `~/.git/hooks/pre-receive` hook.

**Comment by hardik-shah1** [comment]
@marshalhayes I am finding this need very useful, any idea when this is available ?

Or any other way you know by which we can validate commit messages on server side in git-bucket ?

**Comment by marshalhayes** [comment]
It’s great to see you have a need for this.  

I don’t know exactly how much work would be involved here, but I can take a look sometime in the coming weeks.

**Comment by marshalhayes** [comment]
Just pushed this change. e17690ca256df6d495b058cd5c88f5598f1cf3b6

@hardik-shah1, do you have the capability to test it? The most simple way would be to:
1. build from `preReceive`,
2. plop the `.jar` in the GitBucket plugins folder,
3. and add `pre-receive` to a repository's hooks folder

If the `pre-receive` hook executes, then I can start a PR to merge this into the main branch.

**Comment by marshalhayes** [comment]
Before this can work, I need to change a few things. 

`preReceive` upon non-zero status code needs to reject the commit. This can be accomplished by using the exit code from the `HookExecutor.executeHook()` - which isn't used yet - and returning an error message (e.g. `Some("...")`) if the exit code was non-zero. 

I can look at doing this soon - meanwhile I wouldn't spend any time installing the latest version (v1.1.1) until I can make these changes.

**Comment by hardik-shah1** [comment]
@marshalhayes Thank you for the work & update.

**Comment by marshalhayes** [comment]
I'm still working on a solution here. 

So far though, here is where I am: 
- I've changed `HookExecutor.executeHook()` to return a `Tuple3` which represents (in order): (1) the exit code of the `pre-receive` hook, (2) stdout, and (3) stderr.
- I've implemented `ReceiveHook.preReceive()` which now checks the exit code of the `pre-receive` hook. If it is non-zero, it will return a string consisting of standard out and standard error combined. Otherwise, upon a zero status, it will return `None`.

See: 797ec0938d9c921bba51763d8d4df650e498ff59

I'm struggling to setup a way to test this. I hope to make another update soon whenever I can get a test environment stood up.

**Comment by hardik-shah1** [comment]
@marshalhayes  Thanks for your regular updates. My need is changed, I don't need this now. Once again thanks for your help.

**Comment by marshalhayes** [comment]
Oh, okay. Please refer back to this issue if you see a need again.

**Comment by vishal-chitnis** [comment]
@marshalhayes I have a need for `preReceive` hook, is this available.
